name: nabhni
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_svg: null
  get_it: ^8.0.2
  connectivity_plus: ^6.1.0
  lottie: ^3.1.3
  pinput: ^5.0.0

  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  font_awesome_flutter: ^10.8.0
  circular_countdown_timer: ^0.2.4
  carousel_slider: ^5.0.0
  firebase_core: ^3.8.0
dev_dependencies:


  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - Assets/images/
    - Assets/translations/
    - Assets/animations/



  fonts:
    - family: Zain
      fonts:
        - asset: Assets\fonts\Zain-Regular.ttf

          weight: 700

flutter_intl:
  enabled: true
