// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPv6whMxkgX5uU5DwLMHLpZkeGAlyjVlk',
    appId: '1:674632122345:web:a1d04398e22e75abae1578',
    messagingSenderId: '674632122345',
    projectId: 'nabhni-db655',
    authDomain: 'nabhni-db655.firebaseapp.com',
    storageBucket: 'nabhni-db655.firebasestorage.app',
    measurementId: 'G-SEBZGQK69J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjOfMt6KI0m_4DNaSmJRO6VpblsM_n1cI',
    appId: '1:674632122345:android:01fdceea40fcf9cbae1578',
    messagingSenderId: '674632122345',
    projectId: 'nabhni-db655',
    storageBucket: 'nabhni-db655.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqUfdHFvI11vn86RxyG_SDvqLN2f-4Gc',
    appId: '1:674632122345:ios:c206c9c52390447fae1578',
    messagingSenderId: '674632122345',
    projectId: 'nabhni-db655',
    storageBucket: 'nabhni-db655.firebasestorage.app',
    iosBundleId: 'com.example.nabhni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqUfdHFvI11vn86RxyG_SDvqLN2f-4Gc',
    appId: '1:674632122345:ios:c206c9c52390447fae1578',
    messagingSenderId: '674632122345',
    projectId: 'nabhni-db655',
    storageBucket: 'nabhni-db655.firebasestorage.app',
    iosBundleId: 'com.example.nabhni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPv6whMxkgX5uU5DwLMHLpZkeGAlyjVlk',
    appId: '1:674632122345:web:55c6a6c7010e1596ae1578',
    messagingSenderId: '674632122345',
    projectId: 'nabhni-db655',
    authDomain: 'nabhni-db655.firebaseapp.com',
    storageBucket: 'nabhni-db655.firebasestorage.app',
    measurementId: 'G-8MWW9RYRTK',
  );
}
